<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite ignored="0" hostname="yaokaideMacBook-Pro.local" failures="0" tests="9" name="com.tester.cases.KuaiShouTest" time="93.916" errors="7" timestamp="07 Feb 2020 05:35:51 GMT" skipped="0">
  <testcase classname="com.tester.cases.KuaiShouTest" name="product_list" time="0.614"/>
  <testcase classname="com.tester.cases.KuaiShouTest" name="call_nums" time="0.071"/>
  <testcase classname="com.tester.cases.KuaiShouTest" name="share_video" time="15.667">
    <error message="{&quot;code&quot;: -1, &quot;data&quot;: null, &quot;msg&quot;: &quot;ks2: 其他异常错误: Traceback (most recent call last):\n  File \&quot;./utils/deco.py\&quot;, line 37, in wrapper\n    return func(*args, **kwargs)\n  File \&quot;./spider/ks_2/ks_api.py\&quot;, line 787, in get_share_video_info\n    return self.http_post(ks_url, form_params=form_params)\n  File \&quot;./spider/ks_2/ks_api.py\&quot;, line 220, in http_post\n    form_params.update(sign)\nTypeError: &#039;NoneType&#039; object is not iterable\n&quot;, &quot;start_time&quot;: 1581053720, &quot;end_time&quot;: 1581053736}
请求url：http://47.97.206.10/api/ks_v2/share_video?share_url=http://kphbeijing.m.chenzhongtech.com/s/Qsh970xL" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: {"code": -1, "data": null, "msg": "ks2: 其他异常错误: Traceback (most recent call last):\n  File \"./utils/deco.py\", line 37, in wrapper\n    return func(*args, **kwargs)\n  File \"./spider/ks_2/ks_api.py\", line 787, in get_share_video_info\n    return self.http_post(ks_url, form_params=form_params)\n  File \"./spider/ks_2/ks_api.py\", line 220, in http_post\n    form_params.update(sign)\nTypeError: 'NoneType' object is not iterable\n", "start_time": 1581053720, "end_time": 1581053736}
请求url：http://47.97.206.10/api/ks_v2/share_video?share_url=http://kphbeijing.m.chenzhongtech.com/s/Qsh970xL
	at com.tester.cases.KuaiShouTest.share_video(KuaiShouTest.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:282)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:83)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:114)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </error>
  </testcase> <!-- share_video -->
  <testcase classname="com.tester.cases.KuaiShouTest" name="hot_feed" time="15.492">
    <error message="{&quot;code&quot;: -1, &quot;data&quot;: null, &quot;msg&quot;: &quot;ks2: 其他异常错误: Traceback (most recent call last):\n  File \&quot;./utils/deco.py\&quot;, line 37, in wrapper\n    return func(*args, **kwargs)\n  File \&quot;./spider/ks_2/ks_api.py\&quot;, line 663, in get_hot_feed\n    return self.http_post(ks_url, form_params=form_params)\n  File \&quot;./spider/ks_2/ks_api.py\&quot;, line 220, in http_post\n    form_params.update(sign)\nTypeError: &#039;NoneType&#039; object is not iterable\n&quot;, &quot;start_time&quot;: 1581053689, &quot;end_time&quot;: 1581053704}
请求url：http://47.97.206.10/api/ks_v2/hot_feed?page=1&amp;page_size=10" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: {"code": -1, "data": null, "msg": "ks2: 其他异常错误: Traceback (most recent call last):\n  File \"./utils/deco.py\", line 37, in wrapper\n    return func(*args, **kwargs)\n  File \"./spider/ks_2/ks_api.py\", line 663, in get_hot_feed\n    return self.http_post(ks_url, form_params=form_params)\n  File \"./spider/ks_2/ks_api.py\", line 220, in http_post\n    form_params.update(sign)\nTypeError: 'NoneType' object is not iterable\n", "start_time": 1581053689, "end_time": 1581053704}
请求url：http://47.97.206.10/api/ks_v2/hot_feed?page=1&page_size=10
	at com.tester.cases.KuaiShouTest.hot_feed(KuaiShouTest.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:282)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:83)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:114)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </error>
  </testcase> <!-- hot_feed -->
  <testcase classname="com.tester.cases.KuaiShouTest" name="user_info" time="15.520">
    <error message="{&quot;code&quot;: -1, &quot;data&quot;: null, &quot;msg&quot;: &quot;ks2: 其他异常错误: Traceback (most recent call last):\n  File \&quot;./utils/deco.py\&quot;, line 37, in wrapper\n    return func(*args, **kwargs)\n  File \&quot;./spider/ks_2/ks_api.py\&quot;, line 711, in get_user_profile\n    return self.http_post(ks_url, form_params=form_params)\n  File \&quot;./spider/ks_2/ks_api.py\&quot;, line 220, in http_post\n    form_params.update(sign)\nTypeError: &#039;NoneType&#039; object is not iterable\n&quot;, &quot;start_time&quot;: 1581053736, &quot;end_time&quot;: 1581053752}
请求url：http://47.97.206.10/api/ks_v2/user_info?user_id=1391625066" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: {"code": -1, "data": null, "msg": "ks2: 其他异常错误: Traceback (most recent call last):\n  File \"./utils/deco.py\", line 37, in wrapper\n    return func(*args, **kwargs)\n  File \"./spider/ks_2/ks_api.py\", line 711, in get_user_profile\n    return self.http_post(ks_url, form_params=form_params)\n  File \"./spider/ks_2/ks_api.py\", line 220, in http_post\n    form_params.update(sign)\nTypeError: 'NoneType' object is not iterable\n", "start_time": 1581053736, "end_time": 1581053752}
请求url：http://47.97.206.10/api/ks_v2/user_info?user_id=1391625066
	at com.tester.cases.KuaiShouTest.user_info(KuaiShouTest.java:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:282)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:83)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:114)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </error>
  </testcase> <!-- user_info -->
  <testcase classname="com.tester.cases.KuaiShouTest" name="nearby_feed" time="15.551">
    <error message="{&quot;code&quot;: -1, &quot;data&quot;: null, &quot;msg&quot;: &quot;ks2: 其他异常错误: Traceback (most recent call last):\n  File \&quot;./utils/deco.py\&quot;, line 37, in wrapper\n    return func(*args, **kwargs)\n  File \&quot;./spider/ks_2/ks_api.py\&quot;, line 695, in get_nearby_feed\n    return self.http_post(ks_url, form_params=form_params)\n  File \&quot;./spider/ks_2/ks_api.py\&quot;, line 220, in http_post\n    form_params.update(sign)\nTypeError: &#039;NoneType&#039; object is not iterable\n&quot;, &quot;start_time&quot;: 1581053704, &quot;end_time&quot;: 1581053720}
请求url：http://47.97.206.10/api/ks_v2/nearby_feed?page=1&amp;page_size=20&amp;lon=113.712143&amp;lat=34.593717" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: {"code": -1, "data": null, "msg": "ks2: 其他异常错误: Traceback (most recent call last):\n  File \"./utils/deco.py\", line 37, in wrapper\n    return func(*args, **kwargs)\n  File \"./spider/ks_2/ks_api.py\", line 695, in get_nearby_feed\n    return self.http_post(ks_url, form_params=form_params)\n  File \"./spider/ks_2/ks_api.py\", line 220, in http_post\n    form_params.update(sign)\nTypeError: 'NoneType' object is not iterable\n", "start_time": 1581053704, "end_time": 1581053720}
请求url：http://47.97.206.10/api/ks_v2/nearby_feed?page=1&page_size=20&lon=113.712143&lat=34.593717
	at com.tester.cases.KuaiShouTest.nearby_feed(KuaiShouTest.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:282)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:83)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:114)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </error>
  </testcase> <!-- nearby_feed -->
  <testcase classname="com.tester.cases.KuaiShouTest" name="video_comment" time="0.001">
    <error message="Illegal character in query at index 103: http://47.97.206.10/api/ks_v2/video_comment?user_id=191674858&amp;photo_id=5248945383907780546&amp;page_size=10
" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Illegal character in query at index 103: http://47.97.206.10/api/ks_v2/video_comment?user_id=191674858&photo_id=5248945383907780546&page_size=10

	at java.base/java.net.URI.create(URI.java:906)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69)
	at com.tester.cases.KuaiShouTest.video_comment(KuaiShouTest.java:170)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:282)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:83)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:114)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.net.URISyntaxException: Illegal character in query at index 103: http://47.97.206.10/api/ks_v2/video_comment?user_id=191674858&photo_id=5248945383907780546&page_size=10

	at java.base/java.net.URI$Parser.fail(URI.java:2936)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3107)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3195)
	at java.base/java.net.URI$Parser.parse(URI.java:3137)
	at java.base/java.net.URI.<init>(URI.java:623)
	at java.base/java.net.URI.create(URI.java:904)
	... 30 more
]]>
    </error>
  </testcase> <!-- video_comment -->
  <testcase classname="com.tester.cases.KuaiShouTest" name="user_video" time="15.498">
    <error message="{&quot;code&quot;: -1, &quot;data&quot;: null, &quot;msg&quot;: &quot;ks2: 其他异常错误: Traceback (most recent call last):\n  File \&quot;./utils/deco.py\&quot;, line 37, in wrapper\n    return func(*args, **kwargs)\n  File \&quot;./spider/ks_2/ks_api.py\&quot;, line 734, in get_user_feed\n    return self.http_post(ks_url, form_params=form_params)\n  File \&quot;./spider/ks_2/ks_api.py\&quot;, line 220, in http_post\n    form_params.update(sign)\nTypeError: &#039;NoneType&#039; object is not iterable\n&quot;, &quot;start_time&quot;: 1581053752, &quot;end_time&quot;: 1581053767}
请求url：http://47.97.206.10/api/ks_v2/user_video?user_id=1391625066&amp;page_size=10" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: {"code": -1, "data": null, "msg": "ks2: 其他异常错误: Traceback (most recent call last):\n  File \"./utils/deco.py\", line 37, in wrapper\n    return func(*args, **kwargs)\n  File \"./spider/ks_2/ks_api.py\", line 734, in get_user_feed\n    return self.http_post(ks_url, form_params=form_params)\n  File \"./spider/ks_2/ks_api.py\", line 220, in http_post\n    form_params.update(sign)\nTypeError: 'NoneType' object is not iterable\n", "start_time": 1581053752, "end_time": 1581053767}
请求url：http://47.97.206.10/api/ks_v2/user_video?user_id=1391625066&page_size=10
	at com.tester.cases.KuaiShouTest.user_video(KuaiShouTest.java:153)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:282)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:83)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:114)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </error>
  </testcase> <!-- user_video -->
  <testcase classname="com.tester.cases.KuaiShouTest" name="video_detail" time="15.502">
    <error message="{&quot;code&quot;: -1, &quot;data&quot;: null, &quot;msg&quot;: &quot;ks2: 其他异常错误: Traceback (most recent call last):\n  File \&quot;./utils/deco.py\&quot;, line 37, in wrapper\n    return func(*args, **kwargs)\n  File \&quot;./spider/ks_2/ks_api.py\&quot;, line 772, in get_video_info\n    return self.http_post(ks_url, form_params=form_params)\n  File \&quot;./spider/ks_2/ks_api.py\&quot;, line 220, in http_post\n    form_params.update(sign)\nTypeError: &#039;NoneType&#039; object is not iterable\n&quot;, &quot;start_time&quot;: 1581053767, &quot;end_time&quot;: 1581053783}
请求url：http://47.97.206.10/api/ks_v2/video_detail?photo_id=5248945383907780546" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: {"code": -1, "data": null, "msg": "ks2: 其他异常错误: Traceback (most recent call last):\n  File \"./utils/deco.py\", line 37, in wrapper\n    return func(*args, **kwargs)\n  File \"./spider/ks_2/ks_api.py\", line 772, in get_video_info\n    return self.http_post(ks_url, form_params=form_params)\n  File \"./spider/ks_2/ks_api.py\", line 220, in http_post\n    form_params.update(sign)\nTypeError: 'NoneType' object is not iterable\n", "start_time": 1581053767, "end_time": 1581053783}
请求url：http://47.97.206.10/api/ks_v2/video_detail?photo_id=5248945383907780546
	at com.tester.cases.KuaiShouTest.video_detail(KuaiShouTest.java:213)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:282)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:83)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:114)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </error>
  </testcase> <!-- video_detail -->
</testsuite> <!-- com.tester.cases.KuaiShouTest -->
